### ISSUE TITLE
Request to add Greek Cinema channel EPG

### ISSUE THREAD

**Issue by Lelibell** [GreekTVApp/epg-greece-cyprus#1]
Hi Team,

Would it be possible to also include the EPG for Greek Cinema TV channel?

Link to official EPG: http://greekcinematv.com/schedule-australia/

**Comment by 1nikolas** [comment]
They don't seem to provide EPG for next days, it has only for today. Unless I can get their EPG from another site

**Comment by 1nikolas** [comment]
I found their program on CytaVision, I'll add it right now

**Comment by 1nikolas** [comment]
![image](https://user-images.githubusercontent.com/30593419/120164697-7fd09a80-c203-11eb-9c6e-ba2d33cfa597.png)
Done :)
