### ISSUE TITLE
The ert 1, 2 and 3 channels are completely missing from the epg

### ISSUE THREAD

**Issue by pitsi** [GreekTVApp/epg-greece-cyprus#12]
As mentioned in the title, 3 of the 6 ert channels are missing from the epg.xml file since a few days ago. Ertnews, ertsports and ertworld are still there.

Moreover, some channel logos urls lead to 404, e.g.
`https://data.greektv.ml/logos/trt.png`

p.s. Can you also add cosmote's channels? I have read the other issue where a dev says "The Cosmote tv site is very trash, really hard to work with", but iptv-org has some js for it here
https://github.com/iptv-org/epg/tree/master/sites/cosmote.gr

**Comment by KODIKAS-NL** [comment]
> As mentioned in the title, 3 of the 6 ert channels are missing from the epg.xml file since a few days ago. Ertnews, ertsports and ertworld are still there.
> 
> Moreover, some channel logos urls lead to 404, e.g. `https://data.greektv.ml/logos/trt.png`
> 
> p.s. Can you also add cosmote's channels? I have read the other issue a dev says "The Cosmote tv site is very trash, really hard to work with", but iptv-org has some js for it here https://github.com/iptv-org/epg/tree/master/sites/cosmote.gr

Ert seems to have removed Ert1, 2, 3 from ertflix.gr and from the App. The API also doesn't return the EPG data anymore for these channels..
The livestream urls are still working though..
hope it's temporary.

**Comment by pitsi** [comment]
Thank you for the clarfication :)

**Comment by KODIKAS-NL** [comment]
> Thank you for the clarfication :)

If it stays this way, I might look into creating a Cosmote parser myself based on the code you linked too, but I'm pretty occupied with different projects at the moment..

**Comment by 1nikolas** [comment]
> Moreover, some channel logos urls lead to 404, e.g.
https://data.greektv.ml/logos/trt.png

We don't provide logos for everything. You can use your own logos if you want

**Comment by pitsi** [comment]
That is what I do, but I have to admit your logos look great and I may switch to them some day.
If you want, I can search which of those urls lead to a 404 and, if you don't mind waiting, I can create the missing ones in photoshop, since they are all 200*200px png files.

**Comment by 1nikolas** [comment]
I have a parser for cosmote (with json responses) but I don't want to open source it because they will probably close it..

**Comment by 1nikolas** [comment]
> That is what I do, but I have to admit your logos look great and I may switch to them some day.
> If you want, I can search which of those urls lead to a 404 and, if you don't mind waiting, I can create the missing ones in photoshop, since they are all 200*200px png files.

These need time because they have custom backgrounds

**Comment by pitsi** [comment]
What do you mean with custom backgrounds? I can spend some time for them. 
Btw, there are 114 logos in there! :O

**Comment by 1nikolas** [comment]
> What do you mean with custom backgrounds? I can spend some time for them. 
> Btw, there are 114 logos in there! :O 

To make these you need transparent logos which are not available for every channel. That's why it needs time

**Comment by KODIKAS-NL** [comment]
@1nikolas I was curious about the cosmotetv epg so I was looking at the code mentioned by @pitsi and it uses an html lib to grab the info from the html, but while looking up the details on the www.cosmotetv.gr it seems they also have an API which returns JSON?

Like this:
https://www.cosmotetv.gr/portal/residential/program?p_p_id=dayprogram_WAR_OTETVportlet&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_cacheability=cacheLevelPage&_dayprogram_WAR_OTETVportlet_date=09-04-2023&_dayprogram_WAR_OTETVportlet_feedType=EPG&_dayprogram_WAR_OTETVportlet_start=0&_dayprogram_WAR_OTETVportlet_end=15&_dayprogram_WAR_OTETVportlet_platform=DTH&_dayprogram_WAR_OTETVportlet_categoryId=-1

**Comment by 1nikolas** [comment]
@KODIKAS-NL I was talking about another API but this gets the job done I guess

**Comment by KODIKAS-NL** [comment]
> @KODIKAS-NL I was talking about another API but this gets the job done I guess

I'll see if I can create a parser for it

**Comment by KODIKAS-NL** [comment]
> > @KODIKAS-NL I was talking about another API but this gets the job done I guess
> 
> I'll see if I can create a parser for it

that was quite simple: https://github.com/GreekTVApp/epg-greece-cyprus/pull/13

**Comment by pitsi** [comment]
Ert 2 and 3 are back today, ert 1 is still missing.
Can someone post the relevant api url query for ertflix, like the ones above, so as to check it myself?

**Comment by pitsi** [comment]
All three channels seem to be working now. I do not know if anything has changed, e.g. if they are getting scrapped by cosmote's api, but they do have an epg.
If anyone else can confirm it, feel free to close the issue.

Also, thank you very much for the cosmote scrapper :)

**Comment by 1nikolas** [comment]
> > As mentioned in the title, 3 of the 6 ert channels are missing from the epg.xml file since a few days ago. Ertnews, ertsports and ertworld are still there.
> > Moreover, some channel logos urls lead to 404, e.g. `https://data.greektv.ml/logos/trt.png`
> > p.s. Can you also add cosmote's channels? I have read the other issue a dev says "The Cosmote tv site is very trash, really hard to work with", but iptv-org has some js for it here https://github.com/iptv-org/epg/tree/master/sites/cosmote.gr
> 
> I was looking in to fixing this but Ert seems to have removed Ert1, 2, 3 from ertflix.gr and from the App. The API also doesn't return the EPG data anymore for these channels.. The livestream urls are still working though.. hope it's temporary.

Okay I just figured out why it doesn't work, they have geoblocked the epg. So Github Actions that runs with a non greek IP can't access the epgs from ertflix (only for ert world). This is IP based so there is no way to bypass it (even with a greek ertflix account)

**Comment by 1nikolas** [comment]
Fixed it using a proxy 4b21219
