### ISSUE TITLE
Possible to add Rik Sat from source?

### ISSUE THREAD

**Issue by Lelibell** [GreekTVApp/epg-greece-cyprus#14]
Hi team, is it possible to add the channel Rik Sat to the EPG?

Rik’s website has it for rik 1, rik 2 and rik sat for the 7 day minimum you have mentioned in other issue requests. 

Link to Rik’ EPG: http://cybc.com.cy/schedule/

**Comment by 1nikolas** [comment]
this epg source is not good. Doesn't have description and also it stops at 12am and starts at 6-7am. I'm yet to find a good source other than the epg from the sat directly

**Comment by KODIKAS-NL** [comment]
> this epg source is not good. Doesn't have descriptions and also it stops at 12am and starts at 6-7am. I'm yet to find a good source other than the epg from the sat directly

I found a Swiss source, but the titles are in Greeklish : https://tv.blue.ch/tv-guide

Api: https://services.sg101.prd.sctv.ch/catalog/tv/channels/list/(end=202304160400;ids=351;level=minimal;start=202304150400)

**Comment by Lelibell** [comment]
> this epg source is not good. Doesn't have descriptions and also it stops at 12am and starts at 6-7am. I'm yet to find a good source other than the epg from the sat directly

Descriptions: most seem to be there. Try clicking a handful of programs down the schedule 
6am start: do they broadcast between midnight and 6am? Might be the reason it stops

**Comment by devnullpointer** [comment]
Why not just pull it from Nova EPG? They have a filler from 23h00 to 06h00.

**Comment by 1nikolas** [comment]
> Why not just pull it from Nova EPG? They have a filler from 23h00 to 06h00.

![image](https://github.com/GreekTVApp/epg-greece-cyprus/assets/30593419/b866aef7-7281-48c9-84d9-a9e227a95d6a)
that does not look like epg to me

**Comment by edisionnano** [comment]
> > this epg source is not good. Doesn't have descriptions and also it stops at 12am and starts at 6-7am. I'm yet to find a good source other than the epg from the sat directly
> 
> I found a Swiss source, but the titles are in Greeklish : https://tv.blue.ch/tv-guide
> 
> Api: https://services.sg101.prd.sctv.ch/catalog/tv/channels/list/(end=202304160400;ids=351;level=minimal;start=202304150400)

This now has the same RIK SAT epg as nova by the way

**Comment by KODIKAS-NL** [comment]
Looks like RIK now has decent EPG info on their site for RIK SAT : https://tv.rik.cy/schedule/
BUT the html page is fully generated server side, so no JSON or anything containing de program information 😩

Parsing this will take some work... maybe I'll try it, but at the moment I don't have time for it..
<img width="1570" alt="image" src="https://github.com/GreekTVApp/epg-greece-cyprus/assets/58047787/018d5937-6199-4722-ac17-45d08495491f">

**Comment by edisionnano** [comment]
> Looks like RIK now has decent EPG info on their site for RIK SAT : https://tv.rik.cy/schedule/ BUT the html page is fully generated server side, so no JSON or anything containing de program information 😩
> 
> Parsing this will take some work... maybe I'll try it, but at the moment I don't have time for it.. <img alt="image" width="1570" src="https://private-user-images.githubusercontent.com/58047787/325249003-018d5937-6199-4722-ac17-45d08495491f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNzk1NjIsIm5iZiI6MTcxNTE3OTI2MiwicGF0aCI6Ii81ODA0Nzc4Ny8zMjUyNDkwMDMtMDE4ZDU5MzctNjE5OS00NzIyLWFjMTctNDVkMDg0OTU0OTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDE0NDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ODM4ZGExMzE5MTEyNjFmYTFjNGY2Mzg1ODE4NWZjODEwODhkOWVjNTc1ZWIxNDc2NTUxMDI0OTcwMTUxMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zVknRKB-ihloS4E09iYHbM5uounZt8wdLhOFV12DPkY">

The quality is pretty dreadful, sometimes channels are present twice, sometimes aren't present at all, it's not even 24H
