### ISSUE TITLE
I need help on how to add the links to my iptv app on apple tv..  is it with m3u? how do i upload the files?

### ISSUE THREAD

**Issue by AndysChristofi** [GreekTVApp/epg-greece-cyprus#17]

**Comment by 1nikolas** [comment]
This doesn't have channel links, it only has the program (epg)

**Comment by AndysChristofi** [comment]
Where can i access the channel links with m3u?On 7 Apr 2024, at 20:14, Nikolas Spiridakis ***@***.***> wrote:﻿
This doesn't have channel links, it only has the program (epg)
