### ISSUE TITLE
[Question & Request]

### ISSUE THREAD

**Issue by johntaxmi** [GreekTVApp/epg-greece-cyprus#6]
Question: Is it possible to update the Genre, beacuse every channel has genre: Other/Uknown?
Request 1: Is it possible to add support for the Cosmote TV channels? Sports & Cinema?
Request 2: Is it possible to add support for Nova Sports 1 & Nova Sports Start & Nova Sports News?
Thanks in advanced.

**Comment by 1nikolas** [comment]
> Is it possible to update the Genre
I don't think any provider has Genre information 

> Is it possible to add support for the Cosmote TV
If we find any good provider yes. The Cosmote tv site is very trash, really hard to work with


> Is it possible to add support for Nova
Maybe I can work on this if I have time

**Comment by johntaxmi** [comment]
The iptv-org/epg github page, actually has support for Cosmote TV channels but also has the Genre information.
You may try getting the idea of how it works from there.
Maybe only Cosmote TV has the genre visible?

**Comment by 1nikolas** [comment]
> The iptv-org/epg github page, actually has support for Cosmote TV channels but also has the Genre information.

Yeah but it doesn't have descriptions.. You have to make separate requests for that which is very time consuming to do for every single program. It's not worth taking epg from there just for the genre

**Comment by johntaxmi** [comment]
Hello. Coming back to this.
Is it possible to add support for the following channels?

- NOVA SPORTS NEWS
- NOVA SPORTS START
- NOVA SPORTS 1
- NOVA SPORTS 6
- NOVA SPORTS PREMIER LEAGUE
- NOVA SPORTS EXTRA 1
- NOVA SPORTS EXTRA 2
- NOVA SPORTS EXTRA 3
- NOVA SPORTS EXTRA 4

Thanks in advanced!

**Comment by johntaxmi** [comment]
Returing back to this.
I saw that you updated some Novasports channels.
Is it possible to add support for all the rest Novasports channels?

- NOVASPORTS PREMIER LEAGUE
- NOVASPORTS NEWS
- NOVASPORTS 1
- NOVA CINEMA 1
- NOVA CINEMA 2
- NOVA CINEMA 3
- NOVA CINEMA 4

Also, I am not sure if you are able to add support for the Cosmote Sport channels aswell?

**Comment by 1nikolas** [comment]
We can add only channels from [here](https://data.cytavision.com.cy/epg/index.php?lang=el). If you see any channel in cytavision that we don't have let us know otherwise currently we can't add more. Also cosmote is not possible
