### ISSUE TITLE
EPG stopped working

### ISSUE THREAD

**Issue by manifest0** [GreekTVApp/epg-greece-cyprus#7]
Hi, the EPG stopped working and in some cases, it shows the wrong EPG.

**Comment by 1nikolas** [comment]
I know and I'll fix it. I'll write some new code for all this

**Comment by 1nikolas** [comment]
I think it works now, take a look

**Comment by manifest0** [comment]
Thank you 1nikolas, I had just checked it and it works well, thank you!
Some channels such as cytavision sports are missing though, will they be added in the future?

**Comment by 1nikolas** [comment]
I'll add cytavision sports now

**Comment by 1nikolas** [comment]
I added all the sports channels from cyta

**Comment by hadjistasi** [comment]
Hi, how can I watch sports channels from cyta from EPG? I am confused

**Comment by 1nikolas** [comment]
Epg is for the program only. You can't watch these channels here

**Comment by hadjistasi** [comment]
Oh I see. Do you happen to know any decent iptv that shows Greek/Cypriot VIP Sports chanels?

**Comment by 1nikolas** [comment]
@hadjistasi  No
