### ISSUE TITLE
Wrong time in Plex.tv possible due to DST

### ISSUE THREAD

**Issue by gpapathanasiou** [GreekTVApp/epg-greece-cyprus#8]
I  am using the xml file in Plex.tv but is seems that all content in Plex live TV starts an hour earlier.

**Comment by 1nikolas** [comment]
Looks like a plex bug. The timezones are put correctly into the xml (unless maybe the days before the time change). It has the time relative to UTC and it's +2 or +3 depending on the time of the year.
Unless there is a problem with some specific channels

**Comment by gpapathanasiou** [comment]
I downloaded the xml file and replaced +0300 with +0200. I loaded the modified xml in plex and live tv guide is fine. I you check the xml file you can't find any program that starts with +0200. Maybe something isn't working with the rule time of the year.

**Comment by 1nikolas** [comment]
wait we have +2 now. I should fix this

**Comment by gpapathanasiou** [comment]
Yes. Thank you so much for your work! 
Καλό μεσημέρι!

**Comment by 1nikolas** [comment]
Now it should work. I had hardcoded +3 for some stupid reason. Thanks for letting me know
